// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_Microsoft_Windows_AI_MachineLearning_0_H
#define WINRT_Microsoft_Windows_AI_MachineLearning_0_H
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    struct HResult;
}
WINRT_EXPORT namespace winrt::Microsoft::Windows::AI::MachineLearning
{
    enum class ExecutionProviderReadyResultState : int32_t
    {
        InProgress = 0,
        Success = 1,
        Failure = 2,
    };
    enum class ExecutionProviderReadyState : int32_t
    {
        Ready = 0,
        NotReady = 1,
        NotPresent = 2,
    };
    struct IExecutionProvider;
    struct IExecutionProviderCatalog;
    struct IExecutionProviderCatalogStatics;
    struct IExecutionProviderReadyResult;
    struct ExecutionProvider;
    struct ExecutionProviderCatalog;
    struct ExecutionProviderReadyResult;
    struct MachineLearningContract;
}
namespace winrt::impl
{
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProvider>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalog>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalogStatics>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderReadyResult>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResultState>{ using type = enum_category; };
    template <> struct category<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyState>{ using type = enum_category; };
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider> = L"Microsoft.Windows.AI.MachineLearning.ExecutionProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog> = L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult> = L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResult";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResultState> = L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResultState";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyState> = L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyState";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProvider> = L"Microsoft.Windows.AI.MachineLearning.IExecutionProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalog> = L"Microsoft.Windows.AI.MachineLearning.IExecutionProviderCatalog";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalogStatics> = L"Microsoft.Windows.AI.MachineLearning.IExecutionProviderCatalogStatics";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderReadyResult> = L"Microsoft.Windows.AI.MachineLearning.IExecutionProviderReadyResult";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::AI::MachineLearning::MachineLearningContract> = L"Microsoft.Windows.AI.MachineLearning.MachineLearningContract";
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProvider>{ 0xD541C2BF,0x4A51,0x5804,{ 0x8E,0x44,0x2B,0xDF,0x21,0x60,0xC3,0xA1 } }; // D541C2BF-4A51-5804-8E44-2BDF2160C3A1
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalog>{ 0x1DC174C1,0x5C7F,0x54EC,{ 0xAF,0x7A,0x9F,0x3C,0xBF,0x23,0x00,0x97 } }; // 1DC174C1-5C7F-54EC-AF7A-9F3CBF230097
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalogStatics>{ 0x550DEF98,0x2611,0x5433,{ 0xAF,0xB8,0x43,0x67,0x3B,0x61,0x08,0x48 } }; // 550DEF98-2611-5433-AFB8-43673B610848
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderReadyResult>{ 0x91C1724D,0x93C7,0x5284,{ 0xAD,0xBE,0xBA,0x2B,0xD7,0xBE,0x7C,0x79 } }; // 91C1724D-93C7-5284-ADBE-BA2BD7BE7C79
    template <> struct default_interface<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>{ using type = winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProvider; };
    template <> struct default_interface<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>{ using type = winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalog; };
    template <> struct default_interface<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>{ using type = winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderReadyResult; };
    template <> struct abi<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProvider>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Name(void**) noexcept = 0;
            virtual int32_t __stdcall get_LibraryPath(void**) noexcept = 0;
            virtual int32_t __stdcall get_ReadyState(int32_t*) noexcept = 0;
            virtual int32_t __stdcall EnsureReadyAsync(void**) noexcept = 0;
            virtual int32_t __stdcall TryRegister(bool*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalog>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall FindAllProviders(uint32_t* __resultSize, void***) noexcept = 0;
            virtual int32_t __stdcall EnsureAndRegisterAllAsync(void**) noexcept = 0;
            virtual int32_t __stdcall RegisterAllAsync(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalogStatics>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall GetDefault(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderReadyResult>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Status(int32_t*) noexcept = 0;
            virtual int32_t __stdcall get_ExtendedError(winrt::hresult*) noexcept = 0;
            virtual int32_t __stdcall get_DiagnosticText(void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Microsoft_Windows_AI_MachineLearning_IExecutionProvider
    {
        [[nodiscard]] auto Name() const;
        [[nodiscard]] auto LibraryPath() const;
        [[nodiscard]] auto ReadyState() const;
        auto EnsureReadyAsync() const;
        auto TryRegister() const;
    };
    template <> struct consume<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProvider>
    {
        template <typename D> using type = consume_Microsoft_Windows_AI_MachineLearning_IExecutionProvider<D>;
    };
    template <typename D>
    struct consume_Microsoft_Windows_AI_MachineLearning_IExecutionProviderCatalog
    {
        auto FindAllProviders() const;
        auto EnsureAndRegisterAllAsync() const;
        auto RegisterAllAsync() const;
    };
    template <> struct consume<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalog>
    {
        template <typename D> using type = consume_Microsoft_Windows_AI_MachineLearning_IExecutionProviderCatalog<D>;
    };
    template <typename D>
    struct consume_Microsoft_Windows_AI_MachineLearning_IExecutionProviderCatalogStatics
    {
        auto GetDefault() const;
    };
    template <> struct consume<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderCatalogStatics>
    {
        template <typename D> using type = consume_Microsoft_Windows_AI_MachineLearning_IExecutionProviderCatalogStatics<D>;
    };
    template <typename D>
    struct consume_Microsoft_Windows_AI_MachineLearning_IExecutionProviderReadyResult
    {
        [[nodiscard]] auto Status() const;
        [[nodiscard]] auto ExtendedError() const;
        [[nodiscard]] auto DiagnosticText() const;
    };
    template <> struct consume<winrt::Microsoft::Windows::AI::MachineLearning::IExecutionProviderReadyResult>
    {
        template <typename D> using type = consume_Microsoft_Windows_AI_MachineLearning_IExecutionProviderReadyResult<D>;
    };
}
#endif
