// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#include "py.Microsoft.Windows.AI.MachineLearning.h"

namespace py::cpp::Microsoft::Windows::AI::MachineLearning
{
    // ----- ExecutionProvider class --------------------

    static PyObject* _new_ExecutionProvider(PyTypeObject* /*unused*/, PyObject* /*unused*/, PyObject* /*unused*/) noexcept
    {
        static_assert(py::py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>::type_name);
        py::set_invalid_activation_error(py::py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>::type_name);
        return nullptr;
    }

    static void _dealloc_ExecutionProvider(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProvider* self) noexcept
    {
        auto tp = Py_TYPE(self);
        std::destroy_at(&self->obj);
        tp->tp_free(self);
        Py_DECREF(tp);
    }

    static PyObject* ExecutionProvider_EnsureReadyAsync(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProvider* self, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_GET_SIZE(args);

        if (arg_count == 0)
        {
            try
            {
                static std::optional<bool> is_overload_present{};

                if (!is_overload_present.has_value())
                {
                    is_overload_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProvider", L"EnsureReadyAsync", 0);
                }

                if (!is_overload_present.value())
                {
                    py::set_arg_count_version_error(0);
                    return nullptr;
                }

                return py::convert([&]()
                {
                    auto _gil = release_gil();
                    return self->obj.EnsureReadyAsync();
                }());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* ExecutionProvider_TryRegister(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProvider* self, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_GET_SIZE(args);

        if (arg_count == 0)
        {
            try
            {
                static std::optional<bool> is_overload_present{};

                if (!is_overload_present.has_value())
                {
                    is_overload_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProvider", L"TryRegister", 0);
                }

                if (!is_overload_present.value())
                {
                    py::set_arg_count_version_error(0);
                    return nullptr;
                }

                return py::convert([&]()
                {
                    auto _gil = release_gil();
                    return self->obj.TryRegister();
                }());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* ExecutionProvider_get_LibraryPath(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProvider* self, void* /*unused*/) noexcept
    {
        try
        {
            static std::optional<bool> is_property_present{};

            if (!is_property_present.has_value())
            {
                is_property_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProvider", L"LibraryPath");
            }

            if (!is_property_present.value())
            {
                PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
                return nullptr;
            }

            return py::convert([&]()
            {
                auto _gil = release_gil();
                return self->obj.LibraryPath();
            }());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* ExecutionProvider_get_Name(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProvider* self, void* /*unused*/) noexcept
    {
        try
        {
            static std::optional<bool> is_property_present{};

            if (!is_property_present.has_value())
            {
                is_property_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProvider", L"Name");
            }

            if (!is_property_present.value())
            {
                PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
                return nullptr;
            }

            return py::convert([&]()
            {
                auto _gil = release_gil();
                return self->obj.Name();
            }());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* ExecutionProvider_get_ReadyState(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProvider* self, void* /*unused*/) noexcept
    {
        try
        {
            static std::optional<bool> is_property_present{};

            if (!is_property_present.has_value())
            {
                is_property_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProvider", L"ReadyState");
            }

            if (!is_property_present.value())
            {
                PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
                return nullptr;
            }

            return py::convert([&]()
            {
                auto _gil = release_gil();
                return self->obj.ReadyState();
            }());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* _assign_array_ExecutionProvider(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        auto array = std::make_unique<py::ComArray<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>>();
        if (!py::cpp::_winrt::Array_Assign(arg, std::move(array)))
        {
            return nullptr;
        }
        Py_RETURN_NONE;
    }

    static PyObject* _from_ExecutionProvider(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        try
        {
            auto return_value = py::convert_to<winrt::Windows::Foundation::IInspectable>(arg);
            return py::convert(return_value.as<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyMethodDef _methods_ExecutionProvider[] = {
        { "ensure_ready_async", reinterpret_cast<PyCFunction>(ExecutionProvider_EnsureReadyAsync), METH_VARARGS, nullptr },
        { "try_register", reinterpret_cast<PyCFunction>(ExecutionProvider_TryRegister), METH_VARARGS, nullptr },
        { "_assign_array_", _assign_array_ExecutionProvider, METH_O | METH_STATIC, nullptr },
        { "_from", reinterpret_cast<PyCFunction>(_from_ExecutionProvider), METH_O | METH_STATIC, nullptr },
        { }};

    static PyGetSetDef _getset_ExecutionProvider[] = {
        { "library_path", reinterpret_cast<getter>(ExecutionProvider_get_LibraryPath), nullptr, nullptr, nullptr },
        { "name", reinterpret_cast<getter>(ExecutionProvider_get_Name), nullptr, nullptr, nullptr },
        { "ready_state", reinterpret_cast<getter>(ExecutionProvider_get_ReadyState), nullptr, nullptr, nullptr },
        { }};

    static PyType_Slot _type_slots_ExecutionProvider[] = {
        { Py_tp_new, reinterpret_cast<void*>(_new_ExecutionProvider) },
        { Py_tp_dealloc, reinterpret_cast<void*>(_dealloc_ExecutionProvider) },
        { Py_tp_methods, reinterpret_cast<void*>(_methods_ExecutionProvider) },
        { Py_tp_getset, reinterpret_cast<void*>(_getset_ExecutionProvider) },
        { }};

    static PyType_Spec type_spec_ExecutionProvider = {
        "winui3._winui3_microsoft_windows_ai_machinelearning.ExecutionProvider",
        sizeof(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProvider),
        0,
        Py_TPFLAGS_DEFAULT,
        _type_slots_ExecutionProvider};

    // ----- ExecutionProviderCatalog class --------------------

    static PyObject* _new_ExecutionProviderCatalog(PyTypeObject* /*unused*/, PyObject* /*unused*/, PyObject* /*unused*/) noexcept
    {
        static_assert(py::py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>::type_name);
        py::set_invalid_activation_error(py::py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>::type_name);
        return nullptr;
    }

    static void _dealloc_ExecutionProviderCatalog(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog* self) noexcept
    {
        auto tp = Py_TYPE(self);
        std::destroy_at(&self->obj);
        tp->tp_free(self);
        Py_DECREF(tp);
    }

    static PyObject* ExecutionProviderCatalog_EnsureAndRegisterAllAsync(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog* self, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_GET_SIZE(args);

        if (arg_count == 0)
        {
            try
            {
                static std::optional<bool> is_overload_present{};

                if (!is_overload_present.has_value())
                {
                    is_overload_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog", L"EnsureAndRegisterAllAsync", 0);
                }

                if (!is_overload_present.value())
                {
                    py::set_arg_count_version_error(0);
                    return nullptr;
                }

                return py::convert([&]()
                {
                    auto _gil = release_gil();
                    return self->obj.EnsureAndRegisterAllAsync();
                }());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* ExecutionProviderCatalog_FindAllProviders(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog* self, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_GET_SIZE(args);

        if (arg_count == 0)
        {
            try
            {
                static std::optional<bool> is_overload_present{};

                if (!is_overload_present.has_value())
                {
                    is_overload_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog", L"FindAllProviders", 0);
                }

                if (!is_overload_present.value())
                {
                    py::set_arg_count_version_error(0);
                    return nullptr;
                }

                return py::convert([&]()
                {
                    auto _gil = release_gil();
                    return self->obj.FindAllProviders();
                }());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* ExecutionProviderCatalog_GetDefault(PyObject* /*unused*/, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_GET_SIZE(args);

        if (arg_count == 0)
        {
            try
            {
                static std::optional<bool> is_overload_present{};

                if (!is_overload_present.has_value())
                {
                    is_overload_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog", L"GetDefault", 0);
                }

                if (!is_overload_present.value())
                {
                    py::set_arg_count_version_error(0);
                    return nullptr;
                }

                return py::convert([&]()
                {
                    auto _gil = release_gil();
                    return winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog::GetDefault();
                }());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* ExecutionProviderCatalog_RegisterAllAsync(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog* self, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_GET_SIZE(args);

        if (arg_count == 0)
        {
            try
            {
                static std::optional<bool> is_overload_present{};

                if (!is_overload_present.has_value())
                {
                    is_overload_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog", L"RegisterAllAsync", 0);
                }

                if (!is_overload_present.value())
                {
                    py::set_arg_count_version_error(0);
                    return nullptr;
                }

                return py::convert([&]()
                {
                    auto _gil = release_gil();
                    return self->obj.RegisterAllAsync();
                }());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* _assign_array_ExecutionProviderCatalog(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        auto array = std::make_unique<py::ComArray<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>>();
        if (!py::cpp::_winrt::Array_Assign(arg, std::move(array)))
        {
            return nullptr;
        }
        Py_RETURN_NONE;
    }

    static PyObject* _from_ExecutionProviderCatalog(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        try
        {
            auto return_value = py::convert_to<winrt::Windows::Foundation::IInspectable>(arg);
            return py::convert(return_value.as<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyMethodDef _methods_ExecutionProviderCatalog[] = {
        { "ensure_and_register_all_async", reinterpret_cast<PyCFunction>(ExecutionProviderCatalog_EnsureAndRegisterAllAsync), METH_VARARGS, nullptr },
        { "find_all_providers", reinterpret_cast<PyCFunction>(ExecutionProviderCatalog_FindAllProviders), METH_VARARGS, nullptr },
        { "register_all_async", reinterpret_cast<PyCFunction>(ExecutionProviderCatalog_RegisterAllAsync), METH_VARARGS, nullptr },
        { "_assign_array_", _assign_array_ExecutionProviderCatalog, METH_O | METH_STATIC, nullptr },
        { "_from", reinterpret_cast<PyCFunction>(_from_ExecutionProviderCatalog), METH_O | METH_STATIC, nullptr },
        { }};

    static PyGetSetDef _getset_ExecutionProviderCatalog[] = {
        { }};

    static PyType_Slot _type_slots_ExecutionProviderCatalog[] = {
        { Py_tp_new, reinterpret_cast<void*>(_new_ExecutionProviderCatalog) },
        { Py_tp_dealloc, reinterpret_cast<void*>(_dealloc_ExecutionProviderCatalog) },
        { Py_tp_methods, reinterpret_cast<void*>(_methods_ExecutionProviderCatalog) },
        { Py_tp_getset, reinterpret_cast<void*>(_getset_ExecutionProviderCatalog) },
        { }};

    static PyType_Spec type_spec_ExecutionProviderCatalog = {
        "winui3._winui3_microsoft_windows_ai_machinelearning.ExecutionProviderCatalog",
        sizeof(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog),
        0,
        Py_TPFLAGS_DEFAULT,
        _type_slots_ExecutionProviderCatalog};

    static PyGetSetDef getset_ExecutionProviderCatalog_Static[] = {
        { }};

    static PyMethodDef methods_ExecutionProviderCatalog_Static[] = {
        { "get_default", reinterpret_cast<PyCFunction>(ExecutionProviderCatalog_GetDefault), METH_VARARGS, nullptr },
        { }};

    static PyType_Slot type_slots_ExecutionProviderCatalog_Static[] = 
    {
        { Py_tp_base, reinterpret_cast<void*>(&PyType_Type) },
        { Py_tp_getset, reinterpret_cast<void*>(getset_ExecutionProviderCatalog_Static) },
        { Py_tp_methods, reinterpret_cast<void*>(methods_ExecutionProviderCatalog_Static) },
        { }
    };

    static PyType_Spec type_spec_ExecutionProviderCatalog_Static = {
        "winui3._winui3_microsoft_windows_ai_machinelearning.ExecutionProviderCatalog_Static",
        static_cast<int>(PyType_Type.tp_basicsize),
        static_cast<int>(PyType_Type.tp_itemsize),
        Py_TPFLAGS_DEFAULT,
        type_slots_ExecutionProviderCatalog_Static};

    // ----- ExecutionProviderReadyResult class --------------------

    static PyObject* _new_ExecutionProviderReadyResult(PyTypeObject* /*unused*/, PyObject* /*unused*/, PyObject* /*unused*/) noexcept
    {
        static_assert(py::py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>::type_name);
        py::set_invalid_activation_error(py::py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>::type_name);
        return nullptr;
    }

    static void _dealloc_ExecutionProviderReadyResult(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult* self) noexcept
    {
        auto tp = Py_TYPE(self);
        std::destroy_at(&self->obj);
        tp->tp_free(self);
        Py_DECREF(tp);
    }

    static PyObject* ExecutionProviderReadyResult_get_DiagnosticText(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult* self, void* /*unused*/) noexcept
    {
        try
        {
            static std::optional<bool> is_property_present{};

            if (!is_property_present.has_value())
            {
                is_property_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResult", L"DiagnosticText");
            }

            if (!is_property_present.value())
            {
                PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
                return nullptr;
            }

            return py::convert([&]()
            {
                auto _gil = release_gil();
                return self->obj.DiagnosticText();
            }());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* ExecutionProviderReadyResult_get_ExtendedError(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult* self, void* /*unused*/) noexcept
    {
        try
        {
            static std::optional<bool> is_property_present{};

            if (!is_property_present.has_value())
            {
                is_property_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResult", L"ExtendedError");
            }

            if (!is_property_present.value())
            {
                PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
                return nullptr;
            }

            return py::convert([&]()
            {
                auto _gil = release_gil();
                return self->obj.ExtendedError();
            }());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* ExecutionProviderReadyResult_get_Status(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult* self, void* /*unused*/) noexcept
    {
        try
        {
            static std::optional<bool> is_property_present{};

            if (!is_property_present.has_value())
            {
                is_property_present = winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResult", L"Status");
            }

            if (!is_property_present.value())
            {
                PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
                return nullptr;
            }

            return py::convert([&]()
            {
                auto _gil = release_gil();
                return self->obj.Status();
            }());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* _assign_array_ExecutionProviderReadyResult(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        auto array = std::make_unique<py::ComArray<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>>();
        if (!py::cpp::_winrt::Array_Assign(arg, std::move(array)))
        {
            return nullptr;
        }
        Py_RETURN_NONE;
    }

    static PyObject* _from_ExecutionProviderReadyResult(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        try
        {
            auto return_value = py::convert_to<winrt::Windows::Foundation::IInspectable>(arg);
            return py::convert(return_value.as<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyMethodDef _methods_ExecutionProviderReadyResult[] = {
        { "_assign_array_", _assign_array_ExecutionProviderReadyResult, METH_O | METH_STATIC, nullptr },
        { "_from", reinterpret_cast<PyCFunction>(_from_ExecutionProviderReadyResult), METH_O | METH_STATIC, nullptr },
        { }};

    static PyGetSetDef _getset_ExecutionProviderReadyResult[] = {
        { "diagnostic_text", reinterpret_cast<getter>(ExecutionProviderReadyResult_get_DiagnosticText), nullptr, nullptr, nullptr },
        { "extended_error", reinterpret_cast<getter>(ExecutionProviderReadyResult_get_ExtendedError), nullptr, nullptr, nullptr },
        { "status", reinterpret_cast<getter>(ExecutionProviderReadyResult_get_Status), nullptr, nullptr, nullptr },
        { }};

    static PyType_Slot _type_slots_ExecutionProviderReadyResult[] = {
        { Py_tp_new, reinterpret_cast<void*>(_new_ExecutionProviderReadyResult) },
        { Py_tp_dealloc, reinterpret_cast<void*>(_dealloc_ExecutionProviderReadyResult) },
        { Py_tp_methods, reinterpret_cast<void*>(_methods_ExecutionProviderReadyResult) },
        { Py_tp_getset, reinterpret_cast<void*>(_getset_ExecutionProviderReadyResult) },
        { }};

    static PyType_Spec type_spec_ExecutionProviderReadyResult = {
        "winui3._winui3_microsoft_windows_ai_machinelearning.ExecutionProviderReadyResult",
        sizeof(py::wrapper::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult),
        0,
        Py_TPFLAGS_DEFAULT,
        _type_slots_ExecutionProviderReadyResult};

    // ----- Microsoft.Windows.AI.MachineLearning Initialization --------------------

    PyDoc_STRVAR(module_doc, "Microsoft.Windows.AI.MachineLearning");

    static PyModuleDef module_def = {
        PyModuleDef_HEAD_INIT,
        "_winui3_microsoft_windows_ai_machinelearning",
        module_doc,
        0,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr};
} // py::cpp::Microsoft::Windows::AI::MachineLearning

PyMODINIT_FUNC PyInit__winui3_microsoft_windows_ai_machinelearning(void) noexcept
{
    using namespace py::cpp::Microsoft::Windows::AI::MachineLearning;

    if (py::import_winrt_runtime() == -1)
    {
        return nullptr;
    }

    py::pyobj_handle module{PyModule_Create(&module_def)};

    if (!module)
    {
        return nullptr;
    }

    auto inspectable_meta_type = py::get_inspectable_meta_type();
    if (!inspectable_meta_type)
    {
        return nullptr;
    }

    auto object_type = py::get_object_type();
    if (!object_type)
    {
        return nullptr;
    }

    py::pyobj_handle object_bases{PyTuple_Pack(1, object_type)};

    if (!object_bases)
    {
        return nullptr;
    }

    py::pytype_handle ExecutionProvider_type{py::register_python_type(module.get(), &type_spec_ExecutionProvider, object_bases.get(), inspectable_meta_type)};
    if (!ExecutionProvider_type)
    {
        return nullptr;
    }

    py::pyobj_handle ExecutionProviderCatalog_Static_bases{PyTuple_Pack(1, reinterpret_cast<PyObject*>(inspectable_meta_type))};
    if (!ExecutionProviderCatalog_Static_bases)
    {
        return nullptr;
    }

    py::pyobj_handle type_ExecutionProviderCatalog_Static{PyType_FromSpecWithBases(&type_spec_ExecutionProviderCatalog_Static, ExecutionProviderCatalog_Static_bases.get())};
    if (!type_ExecutionProviderCatalog_Static)
    {
        return nullptr;
    }

    py::pytype_handle ExecutionProviderCatalog_type{py::register_python_type(module.get(), &type_spec_ExecutionProviderCatalog, object_bases.get(), reinterpret_cast<PyTypeObject*>(type_ExecutionProviderCatalog_Static.get()))};
    if (!ExecutionProviderCatalog_type)
    {
        return nullptr;
    }

    py::pytype_handle ExecutionProviderReadyResult_type{py::register_python_type(module.get(), &type_spec_ExecutionProviderReadyResult, object_bases.get(), inspectable_meta_type)};
    if (!ExecutionProviderReadyResult_type)
    {
        return nullptr;
    }


    return module.detach();
}
