// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include "pybase.h"
static_assert(winrt::check_version(PYWINRT_VERSION, "0.0.0"), "Mismatched Py/WinRT headers.");
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>

#include <winrt/Microsoft.Windows.AI.MachineLearning.h>

namespace py::proj::Microsoft::Windows::AI::MachineLearning
{
}

namespace py
{
    template<>
    inline constexpr const char* buffer_format<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResultState> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyState> = "i";


    template<>
    struct py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResultState>
    {
        static constexpr std::string_view qualified_name = "winui3.microsoft.windows.ai.machinelearning.ExecutionProviderReadyResultState";
        static constexpr const char* module_name = "winui3.microsoft.windows.ai.machinelearning";
        static constexpr const char* type_name = "ExecutionProviderReadyResultState";
    };

    template<>
    struct py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyState>
    {
        static constexpr std::string_view qualified_name = "winui3.microsoft.windows.ai.machinelearning.ExecutionProviderReadyState";
        static constexpr const char* module_name = "winui3.microsoft.windows.ai.machinelearning";
        static constexpr const char* type_name = "ExecutionProviderReadyState";
    };

    template<>
    struct py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>
    {
        static constexpr std::string_view qualified_name = "winui3.microsoft.windows.ai.machinelearning.ExecutionProvider";
        static constexpr const char* module_name = "winui3.microsoft.windows.ai.machinelearning";
        static constexpr const char* type_name = "ExecutionProvider";
    };

    template<>
    struct py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>
    {
        static constexpr std::string_view qualified_name = "winui3.microsoft.windows.ai.machinelearning.ExecutionProviderCatalog";
        static constexpr const char* module_name = "winui3.microsoft.windows.ai.machinelearning";
        static constexpr const char* type_name = "ExecutionProviderCatalog";
    };

    template<>
    struct py_type<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>
    {
        static constexpr std::string_view qualified_name = "winui3.microsoft.windows.ai.machinelearning.ExecutionProviderReadyResult";
        static constexpr const char* module_name = "winui3.microsoft.windows.ai.machinelearning";
        static constexpr const char* type_name = "ExecutionProviderReadyResult";
    };
}

#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

namespace py::impl::Microsoft::Windows::AI::MachineLearning
{
}

namespace py::wrapper::Microsoft::Windows::AI::MachineLearning
{
    using ExecutionProvider = py::winrt_wrapper<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProvider>;
    using ExecutionProviderCatalog = py::winrt_wrapper<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderCatalog>;
    using ExecutionProviderReadyResult = py::winrt_wrapper<winrt::Microsoft::Windows::AI::MachineLearning::ExecutionProviderReadyResult>;
}

namespace py
{
}
